package com.odin.wms.domain.enums;

public enum ReferenceType {
    PURCHASE_ORDER,
    SALES_ORDER,
    PRODUCTION_ORDER,
    TRANSFER_ORDER,
    MANUAL,
    INVENTORY_COUNT,
    RECEIVING_NOTE,
    PUTAWAY_TASK,
    QUARANTINE_TASK,
    INTERNAL_TRANSFER,
    PICKING_ORDER,
    PACKING_ORDER,
    SHIPPING_ORDER
}
