apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odin-crm-backend-secrets
  labels:
    {{- include "odin-crm-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: odin-crm-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: odin-crm/backend/db-password
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: odin-crm/keycloak/client-secret
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: odin-crm/redis/password
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: odin-crm/backend/datasource-url
