apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odin-crm-frontend-secrets
  labels:
    {{- include "odin-crm-frontend.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: odin-crm-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: odin-crm/nextauth/secret
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: odin-crm/keycloak/client-secret
